// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Admin': string;
  'AdminBody': string;
  'NavPanel': string;
}
export const cssExports: CssExports;
export default cssExports;
