// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'bookingButton': string;
  'contentContainer': string;
}
export const cssExports: CssExports;
export default cssExports;
