services:
  db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    container_name: db_postgres
    ports:
      - '5454:5432'
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  test_db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_db
    container_name: testdb_postgres
    ports:
      - '8000:5432'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
volumes:
  db: 
    driver: local