services:
  test_db:
    image: postgres
    restart: always
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test_data
    container_name: testdb_postgres
    ports:
      - '5454:5432'
    volumes: 
      - /tmp:/tmp
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
  